language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on

go_import_path: github.com/gaojunhuicavon/gostream

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
